# Generated by Django 4.2.4 on 2023-08-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO_BINARIO', 'No Binario'), ('TRANSGENERO', 'Transgénero'), ('INTERSEX', 'Intersex'), ('NOT_SAY', 'Prefiero no Decirlo')], default='M', max_length=50, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='M', max_length=50, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
