# Generated by Django 4.2.4 on 2023-08-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_direccion_alter_employee_base_role_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(default='123456789', max_length=50, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
