# Generated by Django 4.2.4 on 2023-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_telefono_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='alias',
            field=models.CharField(default='estoesunaliasdefault', max_length=50, verbose_name='Alias'),
            preserve_default=False,
        ),
    ]
