# Generated by Django 4.2.4 on 2023-08-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_cliente_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='admin_role',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='cliente_role',
            new_name='isCliente',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='employee_role',
            new_name='isEmployee',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='admin_role',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_role',
            new_name='isCliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='employee_role',
            new_name='isEmployee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='admin_role',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='cliente_role',
            new_name='isCliente',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_role',
            new_name='isEmployee',
        ),
    ]
