# Generated by Django 4.2.4 on 2023-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_rename_admin_role_administrador_isadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO_BINARIO', 'No Binario'), ('TRANSGENERO', 'Transgénero'), ('INTERSEX', 'Intersex'), ('NOT_SAY', 'Prefiero no Decirlo')], max_length=50, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True, verbose_name='Sexo'),
        ),
    ]
