# Generated by Django 4.2.4 on 2023-08-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('empresa', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Empresa')),
                ('nui', models.CharField(max_length=25, verbose_name='Cédula/RUC/Pasaporte')),
                ('calle_principal', models.CharField(max_length=150, verbose_name='Calle Principal')),
                ('calle_secundaria', models.CharField(max_length=150, verbose_name='Calle Secundaria')),
                ('nro_casa', models.CharField(max_length=50, verbose_name='Número de Casa')),
                ('pais', models.CharField(choices=[('Ecuador', 'Ecuador')], max_length=50, verbose_name='País')),
                ('estado', models.CharField(choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsáchilas', 'Santo Domingo de los Tsáchilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], max_length=50, verbose_name='Estado/Provincia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('aclaraciones', models.CharField(max_length=150, verbose_name='Aclaraciones')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': ' Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Telefonos',
            },
        ),
    ]
