# Generated by Django 4.2.4 on 2023-08-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefono',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='direccion',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
    ]
