# Generated by Django 4.2.4 on 2023-08-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_telefono_telefono'),
        ('store', '0003_remove_telefono_cliente_remove_telefono_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Creado en:')),
                ('total_de_orden', models.FloatField(verbose_name='Total de la Orden')),
                ('estado', models.CharField(choices=[('Listo', 'Listo para envíar'), ('Entregado al Cliente', 'Entregado al Cliente'), ('En Espera para enviar', 'En espera para enviar'), ('Enviado al Cliente', 'Enviado al Cliente'), ('Orden preparandose para enviar', 'Orden en Preparacion')], max_length=50, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='usuarios.cliente')),
                ('direccion_de_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='usuarios.direccion')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
