# Generated by Django 4.2.4 on 2023-08-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_producto_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_height',
            field=models.PositiveIntegerField(default=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='image_width',
            field=models.PositiveIntegerField(default=800),
            preserve_default=False,
        ),
    ]
