# Generated by Django 4.2.4 on 2023-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_created_order_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='enDescuento',
            field=models.BooleanField(default=False, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='enDestacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
